import AppKit
import Combine
import Defaults
import SwiftUI

struct ClipboardItem: Identifiable, Equatable {
  struct ImagePayload: Equatable {
    let data: Data
    /// Keep the actual representation type. Writing PNG bytes back under `.tiff` makes the
    /// resulting pasteboard entry unreadable in some receiving apps.
    let pasteboardTypeRawValue: String
  }

  enum Kind: Equatable {
    case text(String)
    case fileURL(URL)
    case image(ImagePayload)
  }
  let id = UUID()
  let kind: Kind
  let date: Date

  var icon: String {
    switch kind {
    case .text: "text.alignleft"
    case .fileURL: "doc"
    case .image: "photo"
    }
  }

  var preview: String {
    switch kind {
    case .text(let s): s.trimmingCharacters(in: .whitespacesAndNewlines)
    case .fileURL(let url): url.lastPathComponent
    case .image: "Image"
    }
  }

  var retainedByteCount: Int {
    switch kind {
    case .text(let string): string.lengthOfBytes(using: .utf8)
    case .fileURL(let url): url.path.lengthOfBytes(using: .utf8)
    case .image(let payload): payload.data.count
    }
  }
}

enum ClipboardPrivacyPolicy {
  static let maximumTextBytes = 64 * 1024
  static let maximumImageBytes = 12 * 1024 * 1024

  /// Pasteboard conventions used by password managers and apps that explicitly mark a copy as
  /// ephemeral. These values are intentionally raw strings because AppKit does not expose typed
  /// constants for the cross-app conventions.
  private static let sensitivePasteboardTypes: Set<String> = Set([
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    "com.agilebits.onepassword",
    "com.agilebits.onepassword.private",
    "com.1password.password",
  ].map { $0.lowercased() })

  static func permits(types: [String]) -> Bool {
    sensitivePasteboardTypes.isDisjoint(with: types.map { $0.lowercased() })
  }

  /// High-confidence secret formats only. Clipboard history is session-only, but credentials
  /// should not be retained in process memory or shown on screen either. Ambiguous short strings
  /// (for example a six-digit number) remain capturable to avoid breaking ordinary copy workflows.
  static func permits(text: String) -> Bool {
    guard text.lengthOfBytes(using: .utf8) <= maximumTextBytes else { return false }
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.isEmpty else { return false }
    let lower = trimmed.lowercased()
    if lower.contains("-----begin ") && lower.contains("private key-----") { return false }
    if lower.hasPrefix("bearer ") {
      let credential = trimmed.dropFirst("bearer ".count)
      if credential.count >= 16, !credential.contains(where: \.isWhitespace) { return false }
    }
    if ["password=", "password:", "passwd=", "client_secret=", "client-secret="].contains(
      where: lower.hasPrefix
    ) {
      return false
    }
    if looksLikeAccessToken(trimmed) || looksLikeJSONWebToken(trimmed) { return false }
    if let components = URLComponents(string: trimmed), components.password != nil { return false }
    return true
  }

  private static func looksLikeAccessToken(_ text: String) -> Bool {
    guard !text.contains(where: \.isWhitespace) else { return false }
    if text.hasPrefix("github_pat_") { return text.count >= 30 }
    if ["ghp_", "gho_", "ghu_", "ghs_", "ghr_"].contains(where: text.hasPrefix) {
      return text.count >= 24
    }
    if text.hasPrefix("sk-") { return text.count >= 20 }
    if text.hasPrefix("AKIA") { return text.count == 20 }
    if text.hasPrefix("ASIA") { return text.count == 20 }
    if text.hasPrefix("AIza") { return text.count >= 30 }
    if ["xoxb-", "xoxp-", "xoxa-", "xoxr-", "xoxs-"].contains(where: text.hasPrefix) {
      return text.count >= 20
    }
    if text.hasPrefix("sk_live_") || text.hasPrefix("rk_live_") { return text.count >= 20 }
    return false
  }

  private static func looksLikeJSONWebToken(_ text: String) -> Bool {
    let segments = text.split(separator: ".", omittingEmptySubsequences: false)
    guard segments.count == 3, segments.allSatisfy({ $0.count >= 8 }) else { return false }
    let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_"))
    return segments.allSatisfy { $0.unicodeScalars.allSatisfy(allowed.contains) }
  }
}

/// Session-only clipboard history: polls the pasteboard, keeps recent copies, and lets you re-copy.
/// Off by default (it would otherwise capture everything copied, including passwords).
@MainActor
final class ClipboardModel: ObservableObject {
  static let shared = ClipboardModel()

  @Published private(set) var items: [ClipboardItem] = []
  @Published private(set) var isPaused = false
  @Published private(set) var lastWriteError: String?
  private let maxItems = 20
  private let maximumRetainedBytes = 32 * 1024 * 1024
  private var lastChange = NSPasteboard.general.changeCount
  private var ownWriteChange = -1
  private var timer: AnyCancellable?
  private var cancellables: Set<AnyCancellable> = []
  private var isRunning = false

  func start() {
    guard !isRunning else { return }
    isRunning = true
    if Defaults[.clipboardEnabled] { startPolling() }
    Defaults.publisher(.clipboardEnabled)
      .dropFirst()
      .sink { [weak self] change in
        if change.newValue { self?.startPolling() } else { self?.stopPolling() }
      }
      .store(in: &cancellables)
  }

  func stop() {
    guard isRunning else { return }
    isRunning = false
    cancellables.removeAll()
    stopPolling()
  }

  private func startPolling() {
    lastChange = NSPasteboard.general.changeCount
    timer = Timer.publish(every: 0.7, on: .main, in: .common).autoconnect()
      .sink { [weak self] _ in self?.poll() }
  }

  private func stopPolling() {
    timer = nil
    items = []
    lastWriteError = nil
  }

  private func poll() {
    let pb = NSPasteboard.general
    guard pb.changeCount != lastChange else { return }
    lastChange = pb.changeCount
    guard pb.changeCount != ownWriteChange else { return }  // ignore our own re-copy
    guard !isPaused else { return }
    capture(pb)
  }

  private func capture(_ pb: NSPasteboard) {
    let rawTypes = (pb.types ?? []).map(\.rawValue)
    guard ClipboardPrivacyPolicy.permits(types: rawTypes) else { return }
    let item: ClipboardItem?
    if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL],
      let url = urls.first, url.isFileURL
    {
      item = ClipboardItem(kind: .fileURL(url), date: Date())
    } else if let str = pb.string(forType: .string), ClipboardPrivacyPolicy.permits(text: str) {
      item = ClipboardItem(kind: .text(str), date: Date())
    } else if let payload = Self.imagePayload(from: pb) {
      item = ClipboardItem(kind: .image(payload), date: Date())
    } else {
      item = nil
    }
    guard let item else { return }
    items.removeAll { $0.kind == item.kind }
    items.insert(item, at: 0)
    if items.count > maxItems { items = Array(items.prefix(maxItems)) }
    while items.reduce(0, { $0 + $1.retainedByteCount }) > maximumRetainedBytes {
      items.removeLast()
    }
  }

  @discardableResult
  func copyBack(_ item: ClipboardItem) -> Bool {
    let pb = NSPasteboard.general
    let succeeded = ClipboardPasteboardTransaction.replace(on: pb) {
      switch item.kind {
      case .text(let s): pb.setString(s, forType: .string)
      case .fileURL(let url): pb.writeObjects([url as NSURL])
      case .image(let payload):
        pb.setData(
          payload.data,
          forType: NSPasteboard.PasteboardType(rawValue: payload.pasteboardTypeRawValue))
      }
    }
    guard succeeded else {
      lastWriteError = "Couldn’t restore that clipboard item."
      return false
    }
    lastWriteError = nil
    ownWriteChange = pb.changeCount
    lastChange = pb.changeCount
    items.removeAll { $0.id == item.id }
    items.insert(item, at: 0)
    return true
  }

  func remove(_ item: ClipboardItem) { items.removeAll { $0.id == item.id } }
  func clear() {
    items = []
    lastWriteError = nil
  }
  func dismissWriteError() { lastWriteError = nil }

  /// Pausing immediately clears retained history. Copies made while paused are deliberately not
  /// backfilled when capture resumes.
  func setPaused(_ paused: Bool) {
    guard isPaused != paused else { return }
    isPaused = paused
    items = []
    lastChange = NSPasteboard.general.changeCount
  }

  private static func imagePayload(from pasteboard: NSPasteboard) -> ClipboardItem.ImagePayload? {
    for type in [NSPasteboard.PasteboardType.tiff, .png] {
      guard let data = pasteboard.data(forType: type),
        data.count <= ClipboardPrivacyPolicy.maximumImageBytes
      else { continue }
      return ClipboardItem.ImagePayload(data: data, pasteboardTypeRawValue: type.rawValue)
    }
    return nil
  }
}

enum ClipboardPasteboardTransaction {
  /// NSPasteboard requires clearing before a write. Clone the current items first and restore them
  /// if the replacement is rejected so a failed history action never destroys the user's clipboard.
  static func replace(on pasteboard: NSPasteboard, write: () -> Bool) -> Bool {
    let previous = (pasteboard.pasteboardItems ?? []).map { source in
      let copy = NSPasteboardItem()
      for type in source.types {
        if let data = source.data(forType: type) { copy.setData(data, forType: type) }
      }
      return copy
    }
    pasteboard.clearContents()
    guard write() else {
      pasteboard.clearContents()
      if !previous.isEmpty { _ = pasteboard.writeObjects(previous) }
      return false
    }
    return true
  }
}

@MainActor
final class ClipboardActivity: NotchActivity, ObservableObject {
  let id = "clipboard"
  let priority = ActivityPriority.ambient
  let tabIcon = "doc.on.clipboard"
  private(set) var activationDate: Date?

  private let model = ClipboardModel.shared
  private var cancellables: Set<AnyCancellable> = []
  private var isMonitoring = false

  var isActive: Bool { Defaults[.clipboardEnabled] && !model.items.isEmpty }

  func start() {
    guard !isMonitoring else { return }
    isMonitoring = true
    model.start()
    model.objectWillChange
      .receive(on: DispatchQueue.main)
      .sink { [weak self] _ in
        guard let self else { return }
        if self.isActive, self.activationDate == nil { self.activationDate = Date() }
        if !self.isActive { self.activationDate = nil }
        self.objectWillChange.send()
      }
      .store(in: &cancellables)
  }

  func stop() {
    guard isMonitoring else { return }
    isMonitoring = false
    cancellables.removeAll()
    model.stop()
    activationDate = nil
    objectWillChange.send()
  }

  var compactLeading: AnyView {
    AnyView(Image(systemName: "doc.on.clipboard").foregroundStyle(.purple).font(.caption2))
  }
  var compactTrailing: AnyView {
    AnyView(
      Text("\(model.items.count)")
        .font(.caption.weight(.semibold)).monospacedDigit().foregroundStyle(.purple))
  }
  var expandedView: AnyView { AnyView(ClipboardView(model: model)) }
}

struct ClipboardView: View {
  @ObservedObject var model: ClipboardModel

  var body: some View {
    VStack(alignment: .leading, spacing: 6) {
      HStack {
        Label("Clipboard", systemImage: "doc.on.clipboard")
          .font(.caption.weight(.semibold)).foregroundStyle(.secondary)
        Spacer()
        Button {
          model.setPaused(!model.isPaused)
        } label: {
          Image(systemName: model.isPaused ? "play.fill" : "pause.fill")
        }
        .buttonStyle(.plain)
        .help(model.isPaused ? "Resume clipboard history" : "Pause and clear clipboard history")
        .accessibilityLabel(
          model.isPaused ? "Resume clipboard history" : "Pause and clear clipboard history")
        if !model.items.isEmpty {
          Button {
            model.clear()
          } label: {
            Image(systemName: "trash")
          }
          .buttonStyle(.plain)
          .help("Clear clipboard history")
          .accessibilityLabel("Clear clipboard history")
        }
      }
      if model.isPaused {
        Text("History paused").font(.caption).foregroundStyle(.secondary)
      } else if let error = model.lastWriteError {
        HStack(spacing: 5) {
          Text(error).font(.caption).foregroundStyle(.orange).lineLimit(1)
          Button("Dismiss") { model.dismissWriteError() }
            .buttonStyle(.link).font(.caption)
        }
      } else if model.items.isEmpty {
        Text("Nothing copied yet").font(.caption).foregroundStyle(.secondary)
      } else {
        ScrollView(.vertical, showsIndicators: false) {
          VStack(spacing: 4) {
            ForEach(model.items) { item in
              Button {
                _ = model.copyBack(item)
              } label: {
                HStack(spacing: 8) {
                  Image(systemName: item.icon).font(.caption2).foregroundStyle(.purple)
                    .frame(width: 16)
                  Text(item.preview).font(.caption).lineLimit(1)
                  Spacer(minLength: 0)
                  Image(systemName: "doc.on.doc").font(.caption2).foregroundStyle(.secondary)
                }
                .padding(.vertical, 3).padding(.horizontal, 6)
                .background(RoundedRectangle(cornerRadius: 6).fill(.white.opacity(0.06)))
                .contentShape(Rectangle())
              }
              .buttonStyle(.plain)
            }
          }
        }
      }
    }
    .foregroundStyle(.white)
    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
  }
}
